{{- if .Values.scripts.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-apps.scriptsConfigMapName" . }}
  labels:
    {{- include "spark-apps.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
{{ (.Files.Glob "scripts/*").AsConfig | indent 2 }}
{{- end }}
