{{- if and .Values.serviceAccount.create .Values.serviceAccount.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "spark-apps.serviceAccountRoleName" . }}
  labels:
    {{- include "spark-apps.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
  {{- toYaml .Values.serviceAccount.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spark-apps.serviceAccountRoleBindingName" . }}
  labels:
    {{- include "spark-apps.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spark-apps.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "spark-apps.serviceAccountRoleName" . }}
{{- end }}