apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/datahub-local/spark-apps
    chart: spark-apps
    targetRevision: 0.1.1
    helm:
      valuesObject:
        serviceAccount:
          create: false
          name: spark
        sparkApplications:
          - name: sample-wordcount
            type: Python
            mode: cluster
            mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
            driver:
              cores: 1
              memory: 512m
            executor:
              instances: 1
              cores: 1
              memory: 512m
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
