apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/datahub-local/datahub-local-workflows.git
    targetRevision: main
    path: workflows/spark-apps
    helm:
      valueFiles:
        - examples/values-example.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
